#%RAML 1.0
title: Sample API
version: v1
baseUri: http://localhost:8081/api

/users:
  get:
    description: Get all users
    responses:
      200:
        body:
          application/json:
            example:
              [
                { "id": 1, "name": "Bharath" }
              ]
